### ISSUE TITLE
Multi languages?

### ISSUE THREAD

**Issue by gladson** [LucasMagnum/pyexplain#11]
Pootle:
https://github.com/translate/pootle

Ou Transifex:
https://github.com/transifex/transifex

**Comment by LucasMagnum** [comment]
É uma possibilidade.
Hoje a idéia é ajudar os iniciantes em português, mas nada impede de expandir isso com a evolução do projeto.

Obrigado mais uma vez @gladson, sua opinião é sempre bem vinda.

**Comment by gladson** [comment]
De nada @LucasMagnum, continue com o trabalho bacana.
